from __future__ import annotations

from typing import Protocol

from app.application.schemas.contact import ContactLinkCreate, ContactLinkUpdate, ContactMessageCreate
from app.infrastructure.db.models import ContactLinkModel, ContactMessageModel


class ContactRepository(Protocol):
    async def list_links(self, include_hidden: bool = False) -> list[ContactLinkModel]: ...
    async def create_link(self, payload: ContactLinkCreate) -> ContactLinkModel: ...
    async def update_link(
        self, link: ContactLinkModel, payload: ContactLinkUpdate
    ) -> ContactLinkModel: ...
    async def delete_link(self, link: ContactLinkModel) -> None: ...
    async def list_messages(self) -> list[ContactMessageModel]: ...
    async def create_message(self, payload: ContactMessageCreate) -> ContactMessageModel: ...

