from __future__ import annotations

from typing import Protocol

from app.application.schemas.project import ProjectCreate, ProjectUpdate
from app.infrastructure.db.models import ProjectModel


class ProjectRepository(Protocol):
    async def list(self, include_unpublished: bool = False) -> list[ProjectModel]: ...
    async def get(self, project_id: int) -> ProjectModel | None: ...
    async def get_by_slug(self, slug: str) -> ProjectModel | None: ...
    async def create(self, payload: ProjectCreate) -> ProjectModel: ...
    async def update(self, project: ProjectModel, payload: ProjectUpdate) -> ProjectModel: ...
    async def delete(self, project: ProjectModel) -> None: ...

